<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Module;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $modules = [
            // Core Modules (Free - Always Enabled)
            [
                'name' => 'dashboard',
                'display_name' => 'Dashboard',
                'description' => 'Company overview and statistics dashboard',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-speedometer2',
                'is_core' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'projects',
                'display_name' => 'Projects',
                'description' => 'Project management and tracking',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-folder',
                'is_core' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'tasks',
                'display_name' => 'Tasks',
                'description' => 'Task assignment and progress tracking',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-list-task',
                'is_core' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'clients',
                'display_name' => 'Clients',
                'description' => 'Client relationship management',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-person-badge',
                'is_core' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'documents',
                'display_name' => 'Documents',
                'description' => 'File management and sharing',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-file-earmark',
                'is_core' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'users',
                'display_name' => 'Team',
                'description' => 'Team member management',
                'category' => Module::CATEGORY_CORE,
                'icon' => 'bi-people',
                'is_core' => true,
                'sort_order' => 6,
            ],

            // Financial Management Modules
            [
                'name' => 'invoicing',
                'display_name' => 'Invoicing & Billing',
                'description' => 'Create invoices, track payments, and manage billing',
                'category' => Module::CATEGORY_FINANCIAL,
                'icon' => 'bi-receipt',
                'price_monthly' => 19.00,
                'price_yearly' => 190.00,
                'sort_order' => 10,
            ],
            [
                'name' => 'estimates',
                'display_name' => 'Estimates & Quotes',
                'description' => 'Generate professional quotes and estimates',
                'category' => Module::CATEGORY_FINANCIAL,
                'icon' => 'bi-calculator',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'sort_order' => 11,
            ],
            [
                'name' => 'expenses',
                'display_name' => 'Expense Tracking',
                'description' => 'Track expenses, receipts, and project costs',
                'category' => Module::CATEGORY_FINANCIAL,
                'icon' => 'bi-credit-card',
                'price_monthly' => 12.00,
                'price_yearly' => 120.00,
                'sort_order' => 12,
            ],
            [
                'name' => 'financial_reports',
                'display_name' => 'Financial Reports',
                'description' => 'Profit & loss, cash flow, and financial analytics',
                'category' => Module::CATEGORY_FINANCIAL,
                'icon' => 'bi-graph-up',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'sort_order' => 13,
            ],
            [
                'name' => 'payments',
                'display_name' => 'Payment Processing',
                'description' => 'Accept online payments and manage transactions',
                'category' => Module::CATEGORY_FINANCIAL,
                'icon' => 'bi-credit-card-2-front',
                'price_monthly' => 29.00,
                'price_yearly' => 290.00,
                'sort_order' => 14,
            ],

            // Advanced Project Management
            [
                'name' => 'gantt_charts',
                'display_name' => 'Gantt Charts & Scheduling',
                'description' => 'Interactive Gantt charts and project scheduling',
                'category' => Module::CATEGORY_PROJECT_MANAGEMENT,
                'icon' => 'bi-calendar3',
                'price_monthly' => 20.00,
                'price_yearly' => 200.00,
                'sort_order' => 20,
            ],
            [
                'name' => 'resource_planning',
                'display_name' => 'Resource Planning',
                'description' => 'Crew scheduling and resource allocation',
                'category' => Module::CATEGORY_PROJECT_MANAGEMENT,
                'icon' => 'bi-person-workspace',
                'price_monthly' => 18.00,
                'price_yearly' => 180.00,
                'sort_order' => 21,
            ],
            [
                'name' => 'time_tracking',
                'display_name' => 'Time Tracking',
                'description' => 'Clock in/out system and timesheet management',
                'category' => Module::CATEGORY_PROJECT_MANAGEMENT,
                'icon' => 'bi-stopwatch',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'sort_order' => 22,
            ],
            [
                'name' => 'quality_control',
                'display_name' => 'Quality Control',
                'description' => 'Inspection checklists and quality management',
                'category' => Module::CATEGORY_PROJECT_MANAGEMENT,
                'icon' => 'bi-shield-check',
                'price_monthly' => 22.00,
                'price_yearly' => 220.00,
                'sort_order' => 23,
            ],
            [
                'name' => 'safety_management',
                'display_name' => 'Safety Management',
                'description' => 'Safety protocols and incident reporting',
                'category' => Module::CATEGORY_PROJECT_MANAGEMENT,
                'icon' => 'bi-shield-exclamation',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'sort_order' => 24,
            ],

            // Field Operations
            [
                'name' => 'mobile_app',
                'display_name' => 'Mobile App',
                'description' => 'Native mobile apps for field operations',
                'category' => Module::CATEGORY_FIELD_OPERATIONS,
                'icon' => 'bi-phone',
                'price_monthly' => 35.00,
                'price_yearly' => 350.00,
                'sort_order' => 30,
            ],
            [
                'name' => 'gps_tracking',
                'display_name' => 'GPS Tracking',
                'description' => 'Real-time location tracking and geofencing',
                'category' => Module::CATEGORY_FIELD_OPERATIONS,
                'icon' => 'bi-geo-alt',
                'price_monthly' => 28.00,
                'price_yearly' => 280.00,
                'sort_order' => 31,
            ],
            [
                'name' => 'equipment_management',
                'display_name' => 'Equipment Management',
                'description' => 'Equipment inventory and maintenance scheduling',
                'category' => Module::CATEGORY_FIELD_OPERATIONS,
                'icon' => 'bi-tools',
                'price_monthly' => 22.00,
                'price_yearly' => 220.00,
                'sort_order' => 32,
            ],
            [
                'name' => 'material_tracking',
                'display_name' => 'Material Tracking',
                'description' => 'Inventory management and material orders',
                'category' => Module::CATEGORY_FIELD_OPERATIONS,
                'icon' => 'bi-boxes',
                'price_monthly' => 20.00,
                'price_yearly' => 200.00,
                'sort_order' => 33,
            ],
            [
                'name' => 'photo_documentation',
                'display_name' => 'Photo Documentation',
                'description' => 'Progress photos and visual documentation',
                'category' => Module::CATEGORY_FIELD_OPERATIONS,
                'icon' => 'bi-camera',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'sort_order' => 34,
            ],

            // Communication & Collaboration
            [
                'name' => 'messaging',
                'display_name' => 'Messaging System',
                'description' => 'Team chat and project communication',
                'category' => Module::CATEGORY_COMMUNICATION,
                'icon' => 'bi-chat-dots',
                'price_monthly' => 12.00,
                'price_yearly' => 120.00,
                'sort_order' => 40,
            ],
            [
                'name' => 'notifications',
                'display_name' => 'Advanced Notifications',
                'description' => 'SMS, email alerts, and custom notification rules',
                'category' => Module::CATEGORY_COMMUNICATION,
                'icon' => 'bi-bell',
                'price_monthly' => 10.00,
                'price_yearly' => 100.00,
                'sort_order' => 41,
            ],
            [
                'name' => 'email_integration',
                'display_name' => 'Email Integration',
                'description' => 'Email sync and automated email campaigns',
                'category' => Module::CATEGORY_COMMUNICATION,
                'icon' => 'bi-envelope',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'sort_order' => 42,
            ],
            [
                'name' => 'client_portal',
                'display_name' => 'Client Portal',
                'description' => 'Dedicated portal for client access and communication',
                'category' => Module::CATEGORY_COMMUNICATION,
                'icon' => 'bi-person-circle',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'sort_order' => 43,
            ],
            [
                'name' => 'vendor_portal',
                'display_name' => 'Vendor Portal',
                'description' => 'Vendor management and communication portal',
                'category' => Module::CATEGORY_COMMUNICATION,
                'icon' => 'bi-building',
                'price_monthly' => 20.00,
                'price_yearly' => 200.00,
                'sort_order' => 44,
            ],

            // Reporting & Analytics
            [
                'name' => 'custom_reports',
                'display_name' => 'Custom Reports',
                'description' => 'Build custom reports and dashboards',
                'category' => Module::CATEGORY_REPORTING,
                'icon' => 'bi-file-bar-graph',
                'price_monthly' => 30.00,
                'price_yearly' => 300.00,
                'sort_order' => 50,
            ],
            [
                'name' => 'business_intelligence',
                'display_name' => 'Business Intelligence',
                'description' => 'Advanced analytics and data visualization',
                'category' => Module::CATEGORY_REPORTING,
                'icon' => 'bi-graph-up-arrow',
                'price_monthly' => 45.00,
                'price_yearly' => 450.00,
                'sort_order' => 51,
            ],
            [
                'name' => 'performance_metrics',
                'display_name' => 'Performance Metrics',
                'description' => 'KPI tracking and performance scorecards',
                'category' => Module::CATEGORY_REPORTING,
                'icon' => 'bi-speedometer',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'sort_order' => 52,
            ],
            [
                'name' => 'compliance_reports',
                'display_name' => 'Compliance Reports',
                'description' => 'Regulatory compliance and audit trails',
                'category' => Module::CATEGORY_REPORTING,
                'icon' => 'bi-shield-check',
                'price_monthly' => 35.00,
                'price_yearly' => 350.00,
                'sort_order' => 53,
            ],
            [
                'name' => 'data_export',
                'display_name' => 'Data Export',
                'description' => 'Export data in multiple formats and API access',
                'category' => Module::CATEGORY_REPORTING,
                'icon' => 'bi-download',
                'price_monthly' => 20.00,
                'price_yearly' => 200.00,
                'sort_order' => 54,
            ],

            // Integration Modules
            [
                'name' => 'accounting_integration',
                'display_name' => 'Accounting Software',
                'description' => 'QuickBooks, Xero, and other accounting integrations',
                'category' => Module::CATEGORY_INTEGRATION,
                'icon' => 'bi-calculator',
                'price_monthly' => 25.00,
                'price_yearly' => 250.00,
                'sort_order' => 60,
            ],
            [
                'name' => 'crm_integration',
                'display_name' => 'CRM Integration',
                'description' => 'Salesforce, HubSpot, and CRM integrations',
                'category' => Module::CATEGORY_INTEGRATION,
                'icon' => 'bi-person-lines-fill',
                'price_monthly' => 30.00,
                'price_yearly' => 300.00,
                'sort_order' => 61,
            ],
            [
                'name' => 'calendar_sync',
                'display_name' => 'Calendar Sync',
                'description' => 'Google Calendar and Outlook integration',
                'category' => Module::CATEGORY_INTEGRATION,
                'icon' => 'bi-calendar-event',
                'price_monthly' => 15.00,
                'price_yearly' => 150.00,
                'sort_order' => 62,
            ],
            [
                'name' => 'weather_api',
                'display_name' => 'Weather API',
                'description' => 'Weather forecasts and project scheduling integration',
                'category' => Module::CATEGORY_INTEGRATION,
                'icon' => 'bi-cloud-sun',
                'price_monthly' => 10.00,
                'price_yearly' => 100.00,
                'sort_order' => 63,
            ],
            [
                'name' => 'supplier_integration',
                'display_name' => 'Material Suppliers',
                'description' => 'Integration with material supplier catalogs',
                'category' => Module::CATEGORY_INTEGRATION,
                'icon' => 'bi-truck',
                'price_monthly' => 20.00,
                'price_yearly' => 200.00,
                'sort_order' => 64,
            ],

            // AI Features
            [
                'name' => 'ai_insights',
                'display_name' => 'AI Project Insights',
                'description' => 'AI-powered project analysis and recommendations',
                'category' => Module::CATEGORY_AI,
                'icon' => 'bi-lightbulb',
                'price_monthly' => 50.00,
                'price_yearly' => 500.00,
                'sort_order' => 70,
            ],
            [
                'name' => 'predictive_analytics',
                'display_name' => 'Predictive Analytics',
                'description' => 'Machine learning for project predictions',
                'category' => Module::CATEGORY_AI,
                'icon' => 'bi-graph-up',
                'price_monthly' => 60.00,
                'price_yearly' => 600.00,
                'sort_order' => 71,
            ],
            [
                'name' => 'risk_assessment',
                'display_name' => 'Risk Assessment',
                'description' => 'AI-powered risk analysis and mitigation',
                'category' => Module::CATEGORY_AI,
                'icon' => 'bi-exclamation-triangle',
                'price_monthly' => 45.00,
                'price_yearly' => 450.00,
                'sort_order' => 72,
            ],
            [
                'name' => 'automated_scheduling',
                'display_name' => 'Automated Scheduling',
                'description' => 'AI-optimized project and resource scheduling',
                'category' => Module::CATEGORY_AI,
                'icon' => 'bi-calendar-check',
                'price_monthly' => 55.00,
                'price_yearly' => 550.00,
                'sort_order' => 73,
            ],
            [
                'name' => 'contract_management',
                'display_name' => 'Contract Management',
                'description' => 'AI-assisted contract analysis and management',
                'category' => Module::CATEGORY_AI,
                'icon' => 'bi-file-text',
                'price_monthly' => 40.00,
                'price_yearly' => 400.00,
                'sort_order' => 74,
            ],
        ];

        foreach ($modules as $moduleData) {
            Module::create($moduleData);
        }
    }
} 